name: "Build and deploy base-metric-service"

on:
  push:
    branches: [staging]
    paths:
      - apps/base-metric-service/**
      - libs/**
      - .github/workflows/base-metric-service.yaml
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare Docker build
        uses: docker/setup-buildx-action@v2

      - name: Login private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCLOUD_DOCKER_REGISTRY }}
          username: ${{ secrets.NCLOUD_STORAGE_ACCESS_KEY }}
          password: ${{ secrets.NCLOUD_STORAGE_SECRET_ACCESS_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/base-metric-service/Dockerfile
          push: true
          tags: ${{ secrets.NCLOUD_DOCKER_REGISTRY }}/base-metric-service:staging
          cache-from: type=registry,ref=${{ secrets.NCLOUD_DOCKER_REGISTRY }}/base-metric-service:buildcache
          cache-to: type=registry,ref=${{ secrets.NCLOUD_DOCKER_REGISTRY }}/base-metric-service:buildcache,mode=max
  deploy:
    name: Deploy to k8s cluster
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up K8s kubeconfig & ncp-iam-authenticator
        run: |
          curl -o ncp-iam-authenticator -L https://github.com/NaverCloudPlatform/ncp-iam-authenticator/releases/latest/download/ncp-iam-authenticator_linux_amd64
          chmod +x ./ncp-iam-authenticator
          mkdir -p $HOME/bin && cp ./ncp-iam-authenticator $HOME/bin/ncp-iam-authenticator && export PATH=$PATH:$HOME/bin
          echo 'export PATH=$PATH:$HOME/bin' >> ~/.bash_profile
          source ~/.bash_profile
          ncp-iam-authenticator help
          mkdir $HOME/.kube
          mkdir $HOME/.ncloud
          touch $HOME/.kube/config
          touch $HOME/.ncloud/configure
          echo "${{ secrets.KUBECONFIG }}"  | base64 -d > $HOME/.kube/config
          echo -e "[DEFAULT]\nncloud_access_key_id = 9BA77460E7645A71CD0E\nncloud_secret_access_key = EBC65AA6E8770D3959C3DA7E1A4A9A179BFFCDC1\nncloud_api_url = https://ncloud.apigw.ntruss.com" > $HOME/.ncloud/configure
          if kubectl get -f infra/staging/services/base-metric-service.yml; then
            kubectl delete -f infra/staging/services/base-metric-service.yml
          fi
          kubectl apply -f infra/staging/services/base-metric-service.yml
