# Source: api/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: location-api
  namespace: default
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: location
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: location-api-service
  namespace: default
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: location
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: location
---
# Source: api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-api
  namespace: default
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: location
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: location
  template:
    metadata:
      labels:
        helm.sh/chart: api-0.1.0
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: location
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: location-api
      containers:
        - name: api
          image: "ninetails-staging.kr.ncr.ntruss.com/location-service:staging"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ninetails-env
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: ninetails-staging