version: '3.8'
services:
  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'